check_update: true

#填写你的Token以激活matrix
access_token: "填写token"

permission_refresh_interval: 60

#bc版本的geyser支持开关
bungee_geysermc_support: false

kick_strike_lightning: true

discord_webhook:
  enable: false
  url: ""

tps_protection:
  enable: true

  min_tps: 18.0

  lag_threshold: 10000

log_file: true

#玩家连接补丁
#如果需要同时使用其他反作弊并且matrix并不兼容那款反作弊的话
#请设为false禁用此选项，以起到兼容效果
#但设为false会导致matrix的移动检测失效
enable_player_connection_patch: true

delete_time: 30

disable_bypass_permission: true

relog_time: 5
#disabled_components似乎已被弃用
disabled_components:
  - "example entry"

custom_vl_weight:
  - "bp.timer:2"
  - "move.invmove:1"
  - "move.vert:5"
  - "move.hor:1"
